### ISSUE TITLE
CreateTransaction - Can I provide the "final price" and avatax will calculate base price + tax so the final result will be the "final price"

### ISSUE THREAD

**Issue by eliezra236** [avadev/AvaTax-REST-V2-JS-SDK#262]
Hi,

I am trying to use Avatax to adjust my prices to include tax.

But I still want the numbers to stay round (I will be the one who will pay the tax).

So if the final price should be 10$, I want avatax to give answer like "8.88 price + 1.12 tax", is that possible?

**Comment by BioSurienDG** [comment]
@eliezra236 Yes, just see this doc: https://developer.avalara.com/avatax/dev-guide/customizing-transaction/using-tax-included

Simply need to use the `taxIncluded` param

**Comment by eliezra236** [comment]
@BioSurienDG Thank you!
