### ISSUE TITLE
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.

### ISSUE THREAD

**Issue by adrianchia** [avadev/AvaTax-REST-V2-JS-SDK#41]
Hi,

When I tried the taxRatesByAddress API on Angular 4, it shows: the following error 
```javascript
TypeError: Failed to execute 'fetch' on 'Window': Request with GET/HEAD method cannot have body.
```
The same method works fine from Node.JS backend application. It turns out that HEAD or GET requests should not have a body, see https://github.com/github/fetch/issues/402, changing from null to undefined resolves the issue.

https://github.com/avadev/AvaTax-REST-V2-JS-SDK/blob/master/lib/AvaTaxClient.js#L2788

**Comment by bogdan-brezuica** [comment]
Hi @han8909227 
I ran into a similar issue for resolveAddress(). Maybe this.restCall() should be called with payload undefined instead of null?
https://github.com/avadev/AvaTax-REST-V2-JS-SDK/blob/master/lib/AvaTaxClient.js#L380

Thanks!

**Comment by rocleegithub** [comment]
Get([FromQuery]ObjectInput input)   
“[FromQuery]”

**Comment by lucaslrc** [comment]
This helped in my API using Golang and Mux.

> Hi @adrianchia
> The problem is that you are making a HTTP GET request, by its definition GET requests don't take request body, instead, GET requests only hits an endpoint with certain parameters embedded in the request url. You may find the format of the request url(query string) [here](https://developer.avalara.com/api-reference/avatax/rest/v2/methods/Free/TaxRatesByAddress/)
> 
> Let me know if you have additional question,
> Han
> 
> [![image](https://user-images.githubusercontent.com/29118945/36876958-9021b1ec-1d6c-11e8-8e85-9a1dbde43ea2.png)](https://developer.avalara.com/resources/conferences/?_ga=2.119288393.1597737374.1519623364-1997382893.1519262471)

This helped in my project with golang using Mux and node-fetch.

**Comment by Mallankur** [comment]
i have also facing the issue i have a lot of Tag Number and I want call the get method  using strin[] TagNumber its show error How can i fix it
