### ISSUE TITLE
TypeError: can't access property 'content-type' of undefined (in browser)

### ISSUE THREAD

**Issue by alexTayanovsky** [avadev/AvaTax-REST-V2-JS-SDK#73]
Happens on this line, and because of this exception, the promise is rejected. 
https://github.com/avadev/AvaTax-REST-V2-JS-SDK/blob/2a9bba520230982683e919ed951f0bd985658590/lib/AvaTaxClient.js#L87

v18.9.0 works fine though

**Comment by contygm** [comment]
addressed in latest releases. Please reopen if the issue persists
