### ISSUE TITLE
v19.3.0 ESModules - Unexpected token import

### ISSUE THREAD

**Issue by AndrewBarba** [avadev/AvaTax-REST-V2-JS-SDK#81]
v19.3.0 seemed to switch to esmodules which makes this no longer compatible with Node without the use of Babel. My guess is this is a release/packaging issue

```
/home/circleci/project/node_modules/avatax/index.js:6
import client from './lib/AvaTaxClient';
^^^^^^

SyntaxError: Unexpected token import
```

**Comment by contygm** [comment]
In 19.3.0, nothing was changed related to esmodules. https://github.com/avadev/AvaTax-REST-V2-JS-SDK/pull/80

Node doesn't support that syntax natively unless using the experimental flag. https://nodejs.org/api/esm.html

**Comment by AndrewBarba** [comment]
How could you close this without testing anything? 19.3.0 does not work on the same versions of node that 19.2.0 works on

**Comment by AndrewBarba** [comment]
You clearly didn't run the build script before publishing to npm...
