### ISSUE TITLE
Integration Test: Upload and download a batch

### ISSUE THREAD

**Issue by justinsoliz** [avadev/AvaTax-REST-V2-JS-SDK#9]
Setup Jest integration test to _upload and download a batch_ per the following swagger spec:
https://sandbox-rest.avatax.com/swagger/ui/index.html#/Batches

**Comment by han8909227** [comment]
Hi @justinsoliz 
To set up testing environment in the JS SDK
- run `npm install` in your terminal, to install all required packages including Jest
- store your credentials in the forms of 
`SANDBOX_USERNAME` and `SANDBOX_PASSWORD`
they must be named this way in order for the test script to fetch correctly, but they can be either clientId/licenseKey pair or username/password pair. 
- run the test suite by `npm run test` this will execute jest

Please let me know if there does not solve your issue,
Han

[![image](https://user-images.githubusercontent.com/29118945/36876958-9021b1ec-1d6c-11e8-8e85-9a1dbde43ea2.png)](https://developer.avalara.com/resources/conferences/?_ga=2.119288393.1597737374.1519623364-1997382893.1519262471)

**Comment by justinsoliz** [comment]
@han8909227 thanks for the pointers, I'll give it a try!

**Comment by contygm** [comment]
Batch integration tests are live and passing with the 18.9 release
